### ISSUE TITLE
Thumbnail isn't shown in the album detail page after uploading an image to S3

### ISSUE THREAD

**Issue by oniono** [aws-samples/amplify-photo-gallery-workshop#10]
After completing the 'Generate Thumbnails' step in the workshop, the thumbnail image did not appear on the screen. In S3 and DDB, data and files were put well, but they were not queried through graphql query. (unauthorized error occured) It seems that the problem is that the photo table in DynamoDB does not have an "owner" data. So, when I look at codes where the "owner" data is added, it is using metadata.owner in the 'workshopphotoprocessor' lambda function. Even after uploading the image to S3 in App.js does not include "owner" in the metadata. So I coded 
let user = await Auth.currentAuthenticatedUser (); 
to add "owner" data to metadata.
Is this right approch?

**Comment by gabehollombe-aws** [comment]
If you're not seeing an 'owner' column in DDB, then I suspect that the app wasn't set up for authentication with Cognito.  Did you complete the previous steps as shown here? https://amplify-workshop.go-aws.com/30_adding_auth.html

If so, would you mind uploading your code to a public repo so I can have a look to try and see what might be wrong?

**Comment by danielbayerlein** [comment]
@gabehollombe-aws I have the same problem. Please have a look at https://amplify-workshop.go-aws.com/60_managing_photos/40_upload_photos_consolidated.html:

The `uploadFile` function sets the metadata for the S3 object, but the `owner` is missing.

```js
// src/App.js

class S3ImageUpload extends React.Component {
  constructor(props) {
    super(props);
    this.state = { uploading: false }
  }

  ...

  uploadFile = async (file) => {
    const fileName = uuid();

    const result = await Storage.put(
      fileName, 
      file, 
      {
        customPrefix: { public: 'uploads/' },
        metadata: { albumid: this.props.albumId }
      }
    );

    console.log('Uploaded file: ', result);
  }

  ...

}
```

If you change the `aws-amplify` import from `import Amplify, { API, graphqlOperation, Storage } from 'aws-amplify';` to `import Amplify, { API, graphqlOperation, Storage, Auth } from 'aws-amplify';` and add the `owner` to the `metadata` object, then it works.

```js
  uploadFile = async (file) => {
    const fileName = uuid();
    const user = await Auth.currentAuthenticatedUser();

    const result = await Storage.put(
      fileName, 
      file, 
      {
        customPrefix: { public: 'uploads/' },
        metadata: { albumid: this.props.albumId, owner: user.username }
      }
    );

    console.log('Uploaded file: ', result);
  }
```

The auth (`@auth(rules: [{allow: owner}])`) is handled in the `schema.graphql` file.

**Comment by gabehollombe-aws** [comment]
Thanks @danielbayerlein!  This must have been a bug introduced accidentally by an update to something else in the workshop content.

Fixed in https://github.com/aws-samples/amplify-photo-gallery-workshop/commit/b69fc3f33a4e9337d5e88800a95781041c7dc260 and re-deployed to the workshop at https://amplify-workshop.go-aws.com/
