### ISSUE TITLE
Do you want to access other resources created in this project from your Lambda function

### ISSUE THREAD

**Issue by vnghia** [aws-samples/amplify-photo-gallery-workshop#11]
I follow the guide and Everything is ok till the chapter "Generating Thumbnails". When I run `amplify function add` it ask me to choose if I want to access other resources created in this project from my Lambda function. I choose no and continue the guide but this does not work at all. As you describe, we will have to access to the storage but I dont know what to do.
My computer: MacOS Mojave

**Comment by gabehollombe-aws** [comment]
Thanks @codelyoko2409 for the bug report.   This is due to recent changes in the Amplify CLI and how it behaves.  I'm working on a fix for you now, but I won't have updated instructions for you until next week.  I'll update you here when I've published a fix.

**Comment by gabehollombe-aws** [comment]
@codelyoko2409  Thanks again for your patience!  

I've published a fix.  https://amplify-workshop.go-aws.com/70_generating_thumbnails/10_creating_a_photo_processor_lambda.html

Try running `amplify function remove` (and removing the workshopphotoprocessor lambda), then try again with the newly published instructions/explanation and let me know how it goes?  I'll leave this open for a few days to wait and hear from you.

**Comment by vnghia** [comment]
@gabehollombe-aws Thanks you for your work.
However, I still can not get it work. I will try again tomorrow and I will tell you what happened

**Comment by gabehollombe-aws** [comment]
@codelyoko2409  Yes please let me know what error you're encountering, and perhaps publish a repo I can look at?  I did my best to do a run-through with the new instructions and I had success. Of course it's possible I missed something in the instructions that I did in the runthrough. More info from you would help.

**Comment by vnghia** [comment]
@gabehollombe-aws Thank you, It work for me. I have a misunderstood between ARN and Latest stream ARN.
