### ISSUE TITLE
Parameters: [triggerFunction] do not exist in the template

### ISSUE THREAD

**Issue by ablbol** [aws-samples/amplify-photo-gallery-workshop#12]
Hi,
I tried the workshop 3 times and every time I get this error at section "CONNECTING THE PHOTOS BUCKET TO THE PROCESSOR FUNCTION"
Could you please assist me in solving it.  I am running the workshop on my Mac.

UPDATE_FAILED               storagephotoalbumsstorage          AWS::CloudFormation::Stack Sat Jul 20 2019 19:36:57 GMT+0400 (Gulf Standard Time) Parameters: [triggerFunction] do not exist in the template

**Comment by b2btvgs** [comment]
Hello -- did you find a solution for this?

I'm getting the same error --  Parameters: [triggerFunction] do not exist in the template

UPDATE_IN_PROGRESS functionworkshopphotoprocessor AWS::CloudFormation::Stack Sat Jul 27 2019 02:07:48 GMT+0000 (UTC) 
⠧ Updating resources in the cloud. This may take a few minutes...

UPDATE_FAILED               storagesafariphotobucket           AWS::CloudFormation::Stack Sat Jul 27 2019 02:07:48 GMT+0000 (UTC) Parameters: [triggerFunction] do not exist in the template

**Comment by ablbol** [comment]
I did not.  However, I tried to do the same thing by first creating a lambda function and giving it the same name in the tutorial.  Then I created storage and when Amplify asked me if I want to trigger a function, I said yes, and passed the name of the function.  Thinks worked this way.

I have a feeling that the tutorial was written a while back.  As you might know, Amplify is moving out fast.

Good luck

**Comment by TheMedina** [comment]
***Update***

I have a solve for the missing trigger function parameter. Apparently amplify no longer handles determining if that trigger needs to exist at this point. The easy fix was modified the parameters.json file to not include the trigger function. Currently it specifies none; however, as the CloudFormation file doesn't prompt us for that, I believe this is why we were getting that error. Removing that from the parameteres.json allowed for a succesful deploy.

Additionally, my other issues we related to an odd time stamp issue of the CF templates in the functions directories. If you follow the directions verbatim it advises you to replace the CF template (which I did not do). I made a backup of the file and even though it was renamed amplify was still using that. So just replace the file as the instructions say.

Let me know if this helps anyone out.

***End of Update****

So I'm having similar issues. These are the three errors the stack outputs in CloudFormation:

The following resource(s) failed to update: [functionworkshopphotoprocessor, storages35b09f15a]. 
Parameters: [DynamoDBPhotosTableArn, S3UserfilesBucketName] do not exist in the template
Parameters: [triggerFunction] do not exist in the template

Has anyone solved for this?

**Comment by tinarastic** [comment]
@TheMedina well done, this worked for me too, thanks

**Comment by gabehollombe-aws** [comment]
Thanks everyone!  I have a packed schedule this week but I'm going to work on testing out (and hopefully merging) https://github.com/aws-samples/amplify-photo-gallery-workshop/pull/13 next week.

**Comment by gabehollombe-aws** [comment]
Closing this issue thanks to merging https://github.com/aws-samples/amplify-photo-gallery-workshop/pull/15
