### ISSUE TITLE
Example auth rules do not secure resources

### ISSUE THREAD

**Issue by RossWilliams** [aws-samples/amplify-photo-gallery-workshop#14]
The example project does not turn off subscriptions to models. This tutorial intends to present a secure solution and guide for new users, but it leaks data through subscriptions. The Amplify documentation states auth rules do not apply subscriptions. Users are advised to turn off subscriptions at the model level or implement their own security.

Please update the example to disable model subscriptions.

**Comment by gabehollombe-aws** [comment]
@RossWilliams  Great catch. This is definitely something I should mention.  As currently written, though, the only info that can leak is Album info, since photo records are created directly in DynamoDB and not via an AppSync mutation.  And, even if you have an album ID, if you're not the owner or a member of the album you won't be able to do a nested fetch for the Albums Photos, right?

So, unless I'm missing something (totally possible, so please continue this discussion), my current feeling is that I should definitely add a notice about this in the workshop to inform people but that the design is probably sufficient for now.  

I'm curious to hear what you think of this though, @RossWilliams

**Comment by RossWilliams** [comment]
Album info contains:
```gql
type Album 
    id: ID!
    name: String!
    owner: String
    members: [String]
    photos: [Photo] @connection(name: "AlbumPhotos")
}
```
This gives away relationships among people, names can suggest where they are (and don't forget the createdAt field). So I can infer who knows who, where they are, what they are doing, and when they are doing it. The multi-user section suggests that users only have access to this information when people are invited, which is not true.

Also, the API design of Photo does not turn off mutations, so an API user could start pushing mutations through AppSync, exposing more data. You should turn off mutations on the Photo model.

My larger concern is that I have a habit of starting a new project with a copy/paste, and AWS seems like a source that will provide a secure solution, especially when i see an @auth directive. This can give me a false sense of security as the API evolves to expose even more personal data. There is an important security responsibility here, and the sample code itself needs to be secure on its own, because I don't think I'm alone in engaging in copy/paste.

**Comment by RossWilliams** [comment]
I looked at this a second time and noticed that your Photo type has a @searchable directive. So any user can run a search and pull out all photo information for all users. It seems as though I could then get the actual photos since I know the id and bucket name. I haven't tested this, but will try tonight. I see you have highlighted the issue [here](https://github.com/aws-amplify/amplify-cli/issues/460#issuecomment-479718925), but don't see how the code sample was updated to deal with this issue.

**Comment by gabehollombe-aws** [comment]
This is great feedback. Thank you @RossWilliams!  I'm aiming to be able to incorporate your suggestion of removing subscriptions (until they support the @auth directive) into the workshop hopefully by the end of next week. I'll keep you posted.

I'll also add a note about the open issue on the @searchable directive not playing well with @auth right now.

**Comment by gabehollombe-aws** [comment]
Update: I'm still working on security related adjustments for the workshop content. However, given the nice developments on subscription auth coming soon here https://github.com/aws-amplify/amplify-cli/issues/1766#issuecomment-522188880 I'm going to wait until that hits the main release, then incorporate that into the content before the next update.  Just keeping ya'll posted here.

**Comment by gabehollombe-aws** [comment]
@RossWilliams  I've just published a new version of the workshop content that uses owner authorization for subscriptions.
