### ISSUE TITLE
Unable to import module 'python_streaming_function': cannot import name 

### ISSUE THREAD

**Issue by leewang19999** [aws-samples/amplify-photo-gallery-workshop#18]
I am following the amplify workshop - Adding Ai(https://amplify-workshop.go-aws.com/110_ai.html). And it comes up some error message in lambda(python_streaming_function.py).

Response:
{
  "errorMessage": "Unable to import module 'python_streaming_function'"
}

Request ID:
"1a82dce6-c263-4bce-9cf0-b28d940813e7"

Function Logs:
START RequestId: 1a82dce6-c263-4bce-9cf0-b28d940813e7 Version: $LATEST
Unable to import module 'python_streaming_function': cannot import name 'BotocoreHTTPSession'.

**Comment by leewang19999** [comment]
Same issue: https://github.com/aws-amplify/amplify-cli/issues/2385

**Comment by gabehollombe-aws** [comment]
This issue was fixed in a newer version of the Amplify CLI. I've recently published a new version of this workshop that uses the new Amplify CLI version.
