### ISSUE TITLE
An error occurred when pushing the resources to the cloud  Unexpected token   in JSON at position 154

### ISSUE THREAD

**Issue by maxhli** [aws-samples/amplify-photo-gallery-workshop#2]
I am following the instructions at: https://amplify-workshop.go-aws.com/70_generating_thumbnails/10_creating_a_photo_processor_lambda.html

Step 9 says ”From the photo-albums directory, run: amplify push to deploy our new function.“ When I run "amplify push", the above error occurs.

The error message is strange because there is no reference to file name, line number and column number. I assume that it refers to the following file: "photo-albums/amplify/backend/function/workshopphotoprocessor/workshopphotoprocessor-cloudformation-template.json". However, I cannot figure out the problem. Please help.
![image](https://user-images.githubusercontent.com/8834738/50911577-ca180d80-13f5-11e9-8694-ff39ee037634.png)

**Comment by gabehollombe-aws** [comment]
Hmm. Could you share a gist of that whole file? Does it pass a JSON validator?

**Comment by maxhli** [comment]
The problem is: I don't know which file is referred in the error message. The error message is vague.

**Comment by maxhli** [comment]
Which JSON validator would you recommend?

**Comment by gabehollombe-aws** [comment]
I like https://jsonlint.com/

**Comment by maxhli** [comment]
The following is full text of the 
workshopphotoprocessor-cloudformation-template.json file.

{
	"AWSTemplateFormatVersion": "2010-09-09",
	"Description": "Lambda resource stack creation using Amplify CLI",
	"Parameters": {
		"S3UserfilesBucketName": {
			"Type": "String"
		},
		"DynamoDBPhotosTableArn": {
			"Type": "String"
		}
	},
	"Resources": {
		"LambdaFunction": {
			"Type": "AWS::Lambda::Function",
			"Properties": {
				"Handler": "index.handler",
				"FunctionName": "workshopphotoprocessor",
				"Role": {
					"Fn::GetAtt": [
						"LambdaExecutionRole",
						"Arn"
					]
				},
				"Runtime": "nodejs8.10",
				"Timeout": "25",
				"Environment": {
					"Variables": {
						"THUMBNAIL_WIDTH": "80",
						"THUMBNAIL_HEIGHT": "80",
						"DYNAMODB_PHOTOS_TABLE_ARN": {
							"Ref": "DynamoDBPhotosTableArn"
						}
					}
				},
				"Code": {
					"S3Bucket": "aipic-20181226163336-deployment",
					"S3Key": "amplify-builds/workshopphotoprocessor-1547049024-latest-build.zip"
				}
			}
		},
		"LambdaExecutionRole": {
			"Type": "AWS::IAM::Role",
			"Properties": {
				"RoleName": "photoalbumsLambdaRole91d2faf3",
				"AssumeRolePolicyDocument": {
					"Version": "2012-10-17",
					"Statement": [
						{
							"Effect": "Allow",
							"Principal": {
								"Service": [
									"lambda.amazonaws.com"
								]
							},
							"Action": [
								"sts:AssumeRole"
							]
						}
					]
				}
			}
		},
		"lambdaexecutionpolicy": {
			"DependsOn": [
				"LambdaExecutionRole"
			],
			"Type": "AWS::IAM::Policy",
			"Properties": {
				"PolicyName": "lambda-execution-policy",
				"Roles": [
					{
						"Ref": "LambdaExecutionRole"
					}
				],
				"PolicyDocument": {
					"Version": "2012-10-17",
					"Statement": [
						{
							"Effect": "Allow",
							"Action": [
								"logs:CreateLogGroup",
								"logs:CreateLogStream",
								"logs:PutLogEvents"
							],
							"Resource": {
								"Fn::Sub": [
									"arn:aws:logs:${region}:${account}:log-group:/aws/lambda/${lambda}:log-stream:*",
									{
										"region": {
											"Ref": "AWS::Region"
										},
										"account": {
											"Ref": "AWS::AccountId"
										},
										"lambda": {
											"Ref": "LambdaFunction"
										}
									}
								]
							}
						}
					]
				}
			}
		},
		"AllPrivsForPhotoAlbums": {
			"DependsOn": [
				"LambdaExecutionRole"
			],
			"Type": "AWS::IAM::Policy",
			"Properties": {
				"PolicyName": "AllPrivsForPhotoAlbums",
				"Roles": [
					{
						"Ref": "LambdaExecutionRole"
					}
				],
				"PolicyDocument": {
					"Version": "2012-10-17",
					"Statement": [
						{
							"Effect": "Allow",
							"Action": [
								"s3:*"
							],
							"Resource": {
								"Fn::Sub": [
									"arn:aws:s3:::${S3UserfilesBucketName}/*",
									{
										"S3UserfilesBucketName": {
											"Ref": "S3UserfilesBucketName"
										}
									}
								]
							}
						}
					]
				}
			}
		},
		"AllPrivsForDynamo": {
			"DependsOn": [
				"LambdaExecutionRole"
			],
			"Type": "AWS::IAM::Policy",
			"Properties": {
				"PolicyName": "AllPrivsForDynamo",
				"Roles": [
					{
						"Ref": "LambdaExecutionRole"
					}
				],
				"PolicyDocument": {
					"Version": "2012-10-17",
					"Statement": [
						{
							"Effect": "Allow",
							"Action": [
								"dynamodb:*"
							],
							"Resource": {
								"Ref": "DynamoDBPhotosTableArn"
							}
						}
					]
				}
			}
		},
		"RekognitionDetectLabels": {
			"DependsOn": [
				"LambdaExecutionRole"
			],
			"Type": "AWS::IAM::Policy",
			"Properties": {
				"PolicyName": "RekognitionDetectLabels",
				"Roles": [
					{
						"Ref": "LambdaExecutionRole"
					}
				],
				"PolicyDocument": {
					"Version": "2012-10-17",
					"Statement": [
						{
							"Effect": "Allow",
							"Action": [
								"rekognition:detectLabels"
							],
							"Resource": "*"
						}
					]
				}
			}
		}
	},
	"Outputs": {
		"Name": {
			"Value": {
				"Ref": "LambdaFunction"
			}
		},
		"Arn": {
			"Value": {
				"Fn::GetAtt": [
					"LambdaFunction",
					"Arn"
				]
			}
		},
		"Region": {
			"Value": {
				"Ref": "AWS::Region"
			}
		}
	}
}

The result says valid JSON".

![image](https://user-images.githubusercontent.com/8834738/51140989-8cf4b680-180d-11e9-9bbe-c69f76710be6.png)

**Comment by sebsto** [comment]
The above JSON is valid, according to JSON Lint.  Do you still experience the issue ?

**Comment by aier-usa** [comment]
Yes, the same issue exists.

**Comment by gabehollombe-aws** [comment]
@aier-usa I've just re-run through the whole workshop from scratch and I didn't encounter the issue you're describing. My only suggestion is to try running through things again. Perhaps you missed a step somewhere along the way or accidentally modified a file in an unexpected way?
