### ISSUE TITLE
Images upload fine (present in bucket) but getPhotos returns empty object

### ISSUE THREAD

**Issue by kross-aeg** [aws-samples/amplify-photo-gallery-workshop#29]
I'm sure this is long-abandoned, but it's fantastic. I did everything in the tutorial, the issue is that uploaded photos never appear on page.  I checked the S3 bucket and they are there and available to the public, but only the album title shows up. Thoughts?

**Comment by gabehollombe-aws** [comment]
Hi @kirkbross !  Not abandoned at all.   In fact, I recently pushed some new updates to this workshop at hosted at https://amplify-workshop.go-aws.com

Were you following along with the most recent content published there (as of ~1 week ago) when you hit this problem?

Can you check the CloudWatch log output for the Lambda S3 Trigger function and share its output here to help me help you debug?

**Comment by kross-aeg** [comment]
@gabehollombe-aws :) I was following https://amplify-workshop.go-aws.com/ — _however_,  I'm **just** realizing that because I already had an aws account configured to us-east-1 from another tutorial, I thought I could skip the "Create a Cloud9 account" part and start with "Getting Started". I'm realizing that thinking that is probably the issue! :) I'm not sure if I can integrate Cloud9 after the fact?

**Comment by gabehollombe-aws** [comment]
So, you totally _can_ do this without Cloud9.  But I find cloud9 helpful for 2 reasons:  1) It normalizes the development environment, which helps when running people through a workshop.  2) It will auto generate and configure AWS credentials for use from within the Cloud9 instance, which helps with deploys and just simplifies the Amplify config step a bit.

You can learn more about Cloud9 here https://aws.amazon.com/cloud9/

I recommend running through the workshop from within cloud9, but you can do it on your own as well.  Note: if you aren't using Cloud9, you will have to re-package the Sharp dependency in the s3 trigger lambda in order for it to work.    See https://sharp.pixelplumbing.com/install#aws-lambda for more info.  Basically, you'll need to remove src/amplify/backend/function/S3Triggerxxxx/src/node_modules/sharp and then run `npm install --arch=x64 --platform=linux --target=10.15.0 sharp` from within the lambda function's src directory, then run `amplify function build` from the photoalbums dir, then do another `amplify function push`

**Comment by kross-aeg** [comment]
@gabehollombe-aws  You rule. Many thanks. If you have a PayPal, I'm happy to contribute :) I'm going to repackage Sharp first and if I can't make it work, I'll just go through from the start in Cloud9. Once I get it working, I'm going to try and refactor it to handle audio uploads with the same type of real time search. My goal being to build a micro Soundcloud-esc type application where there will be images, but audio will be the primary media. 

Unrelated, did you watch the HBO show Silicon Valley?

**Comment by gabehollombe-aws** [comment]
> If you have a PayPal, I'm happy to contribute :) 

No need! I work for AWS and this project is one of my babies. =-)  But thank you for the kind words.

> I'm going to repackage Sharp first and if I can't make it work, I'll just go through from the start in Cloud9. 

OK cool. Please let me know how you go.

> Once I get it working, I'm going to try and refactor it to handle audio uploads with the same type of real time search. My goal being to build a micro Soundcloud-esc type application where there will be images, but audio will be the primary media.

Very cool use case! I'd love to see when you're done.  Let me know if you get stuck on anything else as well.

> Unrelated, did you watch the HBO show Silicon Valley?

I've seen Seasons 1 and 2, why?

**Comment by kross-aeg** [comment]
> I've seen Seasons 1 and 2, why?

Just curious... my brother is an actor and plays Gavin Belson (CEO of Hooli) on the show. I find it ironic I'm a developer in real life and he plays one on TV. :)
