### ISSUE TITLE
Recreate AWS amplify application, after amplify delete command

### ISSUE THREAD

**Issue by ajitgoel** [aws-samples/amplify-photo-gallery-workshop#32]
Hello Gabe,

I have two issues while working through this workshop including

a. AMAZON REKOGNITION not working dynamodb tables not updated with images being uploaded. 
I am assuming that these issues are because I am not using Cloud9 but instead developing on my local windows10 laptop.

The following might be newbie questions. 
b. I had deleted all the AWS resources using `amplify delete `command, to avoid getting charged for aws resources. If I run the `amplify publish` command, I get the `Use amplify init in the root of your app directory to initialize your project with Amplify `error. Does this mean that I have to recreate all the AWS resources from scratch using `amplify init `process? 

c. Would removing the @searchable tag in the schema.graphql allow the application to function without any code changes? I plan to test this out once I get the application running.

d. Instead of running a script that "allows S3 trigger Lambda function to be able to call out to Amazon Rekognition AWS service", can I add the RekognitionPolicy node after lambdaexecutionpolicy node in ~\photoalbums\amplify\backend\function\S3Trigger*\S3Trigger*-cloudformation-template.json? I am asking as I would like these changes to be source controlled and repeatable. 

Many thanks for your input.

**Comment by gabehollombe-aws** [comment]
Hi @ajitgoel 

a. I'm not sure, but I'd just ask for you to try running through the workshop using Cloud9. It gives everyone the same dev env, which helps keep issues like this from cropping up.   

b. Could you please ask this question here: https://github.com/aws-amplify/amplify-cli/issues

c. `@searchable` wires up changes in Dynamo to get sent to an Amazon ElasticSearch  Service domain, plus it creates a new GQL query that lets you easily search against that domain.  If you don't want ES-style searching, you can skip this step.

d. Give it a try. I think that should be fine.
