### ISSUE TITLE
Node version is old

### ISSUE THREAD

**Issue by davep76** [aws-samples/amplify-photo-gallery-workshop#33]
HI Gabe,

As node version is old so amplify command is throwing error. 
Node installation should be changed as below:

> nvm install v12.16.2
> nvm alias default v12.16.2

Thanks

**Comment by gabehollombe-aws** [comment]
I don't think the current version of the workshop instructs you to use NVM anymore. Can you confirm this is still an issue? If so, please just reply here and provide a link please so I can update the content.
