### ISSUE TITLE
Lambda "fails", with "Is not a new file" message

### ISSUE THREAD

**Issue by chris4long** [aws-samples/amplify-photo-gallery-workshop#35]
Hi, 
I may have some other kind of issue, but the record.eventName is often/mostly "ObjectCreated:CompleteMultipartUpload".  I've fixed this, possibly incorrectly, by chaning this line:

*if (record.eventName !== "ObjectCreated:Put") { console.log('Is not a new file'); return; }*

to 

*if ((record.eventName !== "ObjectCreated:Put") && (record.eventName !== "ObjectCreated:CompleteMultipartUpload")) { console.log('Is not a new file: event is'+record.eventName); return; }*
  
Can you confirm that I've got a correct solution here?

Many thanks
Chris 

(great tutorial by the way, good demo of lots of features and techniques).

**Comment by gabehollombe-aws** [comment]
Yep! That fix is just fine!
