### ISSUE TITLE
Subscription onCreatePhoto returns null and crashes frontend

### ISSUE THREAD

**Issue by Nxtra** [aws-samples/amplify-photo-gallery-workshop#48]
When uploading a new photo to an album it triggers the `onCreatePhoto` subscription.

![image](https://user-images.githubusercontent.com/36597466/92988863-a1e88800-f4cf-11ea-91f4-aa936a91df3a.png)

I logged the data coming back from the subscription and indeed it contains `null`.

```
  "value": {
    "data": {
      "onCreatePhoto": null
    },
```

Causing the error:
![image](https://user-images.githubusercontent.com/36597466/92988891-f3911280-f4cf-11ea-8c25-aac73b119e8d.png)

Setting up the subscription in the console and uploading a new photo also returns  `null` when a new photo is uploaded.

I first saw the behaviour when following along with the tutorial. Next I just cloned the repo and deployed it. This gave the same behavior.

How can we fix the above subscription on `onCreatePhoto` so that it does return data?

**Comment by gabehollombe-aws** [comment]
I'm not able to reproduce this issue.  Please see this recording of the workshop step-by-step (up until the point where uploads are tested and thumbnails are visible): https://youtu.be/GAf37PbD4QI

**Comment by Nxtra** [comment]
> I'm not able to reproduce this issue. Please see this recording of the workshop step-by-step (up until the point where uploads are tested and thumbnails are visible): https://youtu.be/GAf37PbD4QI

Okay, I'll try and come back to you.

**Comment by gabehollombe-aws** [comment]
Thanks! Please do let me know if you're able to figure out what the difference is?

**Comment by Nxtra** [comment]
> Thanks! Please do let me know if you're able to figure out what the difference is?

Diving back into it this weekend!

**Comment by Nxtra** [comment]
I followed along with the video. I still have the above problem but found a key difference that might be causing this.
Since I already had the amplify cli installed on my machine, I didn't want to roll back to an older version.

I am currently at `4.29.1`. 
The workshop is at `4.13.2`. 

I suppose a change in the CLI might be the cause. What do you think?

**Comment by gabehollombe-aws** [comment]
Yes, this could 100% be the issue, and it's one of the reasons that I ask folks to use a fresh Cloud9 Instance when running with the workshop, since there is often a lag between when I have an opportunity to refresh the workshop instructions to keep pace with changes in Amplify and dependencies. 

Perhaps try Nader's workshop which covers similar content and is more recently updated? 

https://github.com/dabit3/amplify-photo-sharing-workshop

**Comment by Nxtra** [comment]
Aight thanks.
I'll check that one too. Anyway this must be one of the best workshops I ever did.
