### ISSUE TITLE
Modified Code that support the new env parameter.

### ISSUE THREAD

**Issue by wongcyrus** [aws-samples/amplify-photo-gallery-workshop#5]
I just works on the workshop today and the current version code is not working any more since the new env variable has added.
Here my modified code for your consideration. (I should create a pull request but I don't have time.)
https://drive.google.com/open?id=1p5o0-779Z7MWgv-ZtpFptXY7oBHBej0e 

Here is my demo video with the new code but it is in Cantonese for Hong Kong users.
https://www.youtube.com/watch?v=UBxwLiV-Jyg&feature=youtu.be

**Comment by gabehollombe-aws** [comment]
I've updated the workshop to support Amplify's new env variable and a new build has been published.
See commit: cd7b193b3c6dfd59b050a631a0f8b93858db0f44
