### ISSUE TITLE
Fix Sharp issue when running on MacOS

### ISSUE THREAD

**Issue by peerjako-aws** [aws-samples/amplify-photo-gallery-workshop#9]
For those who doesn't want to use Cloud9 but run the workshop on their Mac, the photo processor function will fail because lambda does not work with the MacOs version of Sharp.

I suggest adding a small tips-box in "10_creating_a_photo_processor_lambda" with the MacOs fix described here:
http://sharp.pixelplumbing.com/en/stable/install/#aws-lambda

rm -rf node_modules/sharp
npm install --arch=x64 --platform=linux --target=8.10.0 sharp

**Comment by ethansmith** [comment]
Agreed, and please make it clear that those commands need to be executed from the .../function/workshopphotoprocessor/src directory. I have a nice palm-to-forehead bruise from realizing I had spent the past hour updating the module in my frontend app.

**Comment by attilam** [comment]
I've had the same problem running under WSL.

This change is important in the CloudFormation template: `"Runtime": "nodejs10.x",`. I skipped over this the first time...

After doing the platform-specific install of Sharp mentioned above the Amplify CLI didn't pick up on the changes. In the end I had to zip the contents of the src folder and upload it in the Lamba console manually.

**Comment by gabehollombe-aws** [comment]
This workshop recommends running on Cloud9 for this very reason. But the comments here in this issue are helpful for folks who are seeking to get things working when running from their own laptops. I'll close this issue but if you feel more discussion or improvements are warranted please reply.

@ethansmith  there are revised instructions now that I hope are more clear at https://amplify-workshop.go-aws.com/70_generating_thumbnails/10_processing_photos_with_the_s3_trigger_lambda_function.html

**Comment by ghost** [comment]
Same issue with WSL, so +1 for the improvement for real world applications (i.e. running on your machine). This workshop material was _incredibly_ helpful to have things like this sideline user experiences.

The above commands for remove and sharp install in src directory worked for me.
